### ISSUE TITLE
显示滚动条问题,按照上次你说的设置CSS,并没有显示呀?

### ISSUE THREAD

**Issue by issmile** [myronliu347/vue-carbon#15]
而且也是包含在content 组件内的
![image](https://cloud.githubusercontent.com/assets/20268011/18614682/138d803a-7dc6-11e6-86c4-6c20dc297ea9.png)
![image](https://cloud.githubusercontent.com/assets/20268011/18614706/9bbf5d48-7dc6-11e6-9add-cbf605a78f25.png)

**Comment by myronliu347** [comment]
Content组件我屏蔽了滚动条，你可以使用自己的 div当做content

``` html
<div class="vc-page">
  <div class="my-content">
   // ....
  </div>
</div>
```

``` css
.my-content {
width: 100%;
  flex: 1;
  overflow: auto;
  -webkit-overflow-scrolling: touch;
  position: relative;
}
```
