### ISSUE TITLE
为什么我引入的bottom Nav 还是顶在最上面的?

### ISSUE THREAD

**Issue by issmile** [myronliu347/vue-carbon#33]
![image](https://cloud.githubusercontent.com/assets/20268011/19799204/fa68bf76-9d27-11e6-8177-6d9c3b543193.png)
代码是原搬过来的,也没看有什么CSS.什么鬼?为什么你的例子就在下面,我的例子就在上面?
  <bottom-nav :active="toolActive" @nav-change="tabClick">
    <bottom-nav-item icon="home" title="首页" ></bottom-nav-item>
    <bottom-nav-item icon="explore" title="发现"></bottom-nav-item>
    <bottom-nav-item icon="person" title="我的"></bottom-nav-item>
  </bottom-nav>

**Comment by myronliu347** [comment]
这个默认是没有设置的 position 的， 你可以给它加样式；

``` css
.demo-bottom {
  position: fixed;
  left: 0;
  right: 0;
  bottom: 0;
}
```
